### Post test: addCompany
POST http://localhost:8080/company
Content-Type: application/json

{
  "ticker": "COKE"
}

### Get test: get companies (page)
GET http://localhost:8080/company


### Get test: search dividends by company name
GET http://localhost:8080/finance/dividend/Coca-Cola Consolidated, Inc.

### Get test: autocomplete test
GET http://localhost:8080/company/autocomplete?keyword=A